CREATE TABLE `person` (
  `sys_id` char(36) NOT NULL,
  `sys_created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sys_created_by` varchar(255) NOT NULL,
  `sys_updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sys_updated_by` varchar(255) NOT NULL,
  `active` tinyint(4) NOT NULL DEFAULT '1',
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `preferred_name` varchar(45) DEFAULT NULL,
  `prefix` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `member_id` varchar(45) NOT NULL,
  `member_type` varchar(255) NOT NULL,
  `phone_home` varchar(20) DEFAULT NULL,
  `phone_business` varchar(20) DEFAULT NULL,
  `phone_cellular` varchar(20) DEFAULT NULL,
  `email` varchar(254) DEFAULT NULL,
  `opt_out_email` tinyint(4) NOT NULL DEFAULT '0',
  `opt_out_phone` tinyint(4) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  `organisation_id` char(36) DEFAULT NULL,
  `organisation` varchar(150) DEFAULT NULL,
  `sys_username` varchar(254) DEFAULT NULL,
  `sys_passwd` varchar(254) DEFAULT NULL,
  `sys_passwd_changed_on` datetime DEFAULT NULL,
  `sys_locked_out` tinyint(4) DEFAULT '0',
  `sys_passwd_reset` tinyint(4) DEFAULT '0',
  `sys_roles` varchar(255) DEFAULT NULL,
  `sys_expire_on` datetime DEFAULT NULL,
  `sys_protected` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`sys_id`),
  UNIQUE KEY `member_id_UNIQUE` (`member_id`),
  KEY `person_name` (`name`) /*!80000 INVISIBLE */,
  KEY `person_organisation` (`organisation_id`) /*!80000 INVISIBLE */,
  KEY `person_username` (`sys_username`),
  CONSTRAINT `fk_person_organisation_id` FOREIGN KEY (`organisation_id`) REFERENCES `organisation` (`sys_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci