CREATE TABLE `organisation` (
  `active` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'Indicates whether this record is activly used in the database application',
  `name` varchar(150) NOT NULL COMMENT 'The name of the organisation',
  `address` varchar(255) DEFAULT NULL COMMENT 'The contact address of the organisation. This may be the street address or postal address.',
  `city` varchar(45) DEFAULT NULL COMMENT 'The city of the contact address of the organisation',
  `state` varchar(45) DEFAULT NULL COMMENT 'The state/province/area/territory of the contact address of the organisation',
  `postal_code` varchar(20) DEFAULT NULL COMMENT 'The postal code/zip of the contact address of the organisation',
  `country` varchar(80) DEFAULT NULL COMMENT 'The county of the contact address of the organisation',
  `phone_business` varchar(20) DEFAULT NULL COMMENT 'The business telephone number of the organisation',
  `phone_emergency` varchar(20) DEFAULT NULL COMMENT 'The emergency telephone number of the organisation',
  `phone_cellular` varchar(20) DEFAULT NULL COMMENT 'The cellular/mobile telephone of the organisation',
  `phone_facsimile` varchar(20) DEFAULT NULL COMMENT 'The facsimile number of the organisation',
  `email` varchar(254) DEFAULT NULL,
  `web_address` varchar(255) DEFAULT NULL,
  `organisation_type` varchar(80) DEFAULT NULL,
  `logo` longblob COMMENT 'An image of the organisations business logo',
  `sys_id` char(36) NOT NULL COMMENT 'Primary key value UUID/GUID',
  `sys_created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date/time when the record was created',
  `sys_created_by` varchar(255) NOT NULL COMMENT 'Identifier of the user that created the record',
  `sys_updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date/time when the record was last updated',
  `sys_updated_by` varchar(255) NOT NULL COMMENT 'Identifier of the user that last updated the record',
  `organisation_id` varchar(50) NOT NULL,
  PRIMARY KEY (`sys_id`),
  UNIQUE KEY `organisation_id_UNIQUE` (`organisation_id`),
  KEY `organisation_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Information about organisations'